### ISSUE TITLE
ImportError: cannot import name '_has_surrogates' from 'email.utils

### ISSUE THREAD

**Issue by ABDOELSHEMY** [JoeyBallentine/Video-Inference#1]
**_hi @JoeyBallentine 
thank you for your great work
when i try to test it, it give me this error_**

PS J:\Sr\Video-Inference-master> python run.py ./models/rife.pth --input "./input/0001.mov" --output "./output/output_video.mp4" --chop_forward
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    import torch
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\__init__.py", line 365, in <module>
    import torch.hub
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\hub.py", line 17, in <module>
    from urllib.request import urlopen
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\email\_policybase.py", line 9, in <module>
    etag: "1603612825"
**ImportError: cannot import name '_has_surrogates' from 'email.utils' (C:\Users\ABDO\AppData\Local\Programs\Python\Python38\lib\email\utils.py)**

**_windows 10
cpu mode_**

how can i solve this please

**Comment by ABDOELSHEMY** [comment]
ok, seem like it is due to i have 2 python version, remove one of them solve the error, i can safely close this now
